### PR TITLE
Another minor improvement for usability

### PR DESCRIPTION
**Pull request by rabdulatipoff**
So I became fed up with those msgboxes which appear after you 'Open ...' a DS folder; IMHO, these may only be useful once when you first start the program, so there's still a checkbox that can be useful for someone who seeks hints. Also the window titlebars seem to contain enough information so you wouldn't have to worry too much about people getting lost either way.

Middle-click for setting the current label (class) for a given bounding box is very useful when your team  works with annotations which may change in the future -- instead of redrawing the boxes, now you can change their labels much easier than before.

### CODE REVIEW

**Comment by developer0hye** [comment]
@rabdulatipoff 
Thanks for your great PR!
After test it, I will merge this, but it will take some time.

**Comment by rabdulatipoff** [comment]
@developer0hye Thanks! The conflict is due to that I was using and editing the program at the same time and stashing my changes properly before pulling 'origin' appeared troublesome (maybe it's my lack of Git knowledge, got to read docs).

**Comment by developer0hye** [comment]
@rabdulatipoff 
Yes, recently I modified the restriction on bounding box size.
Refer to [this issue](https://github.com/developer0hye/Yolo_Label/issues/29).

**Comment by developer0hye** [comment]
@rabdulatipoff 
Coulud you re-send this project pull-request after fixing the conflicts?

**Comment by rabdulatipoff** [comment]
Re-sent now... fixing took me two minutes at most, hopefully

**Pull request closed without merging**
