### PR TITLE
Visualize class names on the bounding box

### PR DESCRIPTION
**Pull request by e8035669**
I also need class names on the bounding box, just like #43 says.
So I try my best to made one, and mimic the "Darknet style". Hope you like it. 😊

By the way, I found `QImage::scaled()` returned an image with different format. It returned an image with `QImage::Format_RGB32` format, then gamma transform would not work perfectly. I has fixed this problem.

These function has been tested on my Manjaro Linux, with Qt 5.15.6

### CODE REVIEW

**Comment by developer0hye** [comment]
@e8035669 
Thanks for your contribution!

I am too busy recently so that I can't check this pr right now. I will check and merge it after I finish my missions.

**Comment by e8035669** [comment]
I agree. Zooming functional, hide some classes, history list and some statistics are great ideas. especially when you have lots of images to deal with, these feature will help them very much.
If you want to implement these feature, You need Qt framework installed, Qt designer IDE is also an important tool to work with GUI design.

**Comment by developer0hye** [comment]
@e8035669  @Kazox61 

I started reviewing this PR.

Thanks for your works and opinions to make a better labeling program.

I think that users can turn off plotting label function because label can occlude objects to be labeled.

So I wanted to turn on and off this option by shortcut. What do you think of this proposal?

Plus, if you agree with my opinion, what shortcut should we choose for this option?

**Comment by developer0hye** [comment]
image

Using radio button for this function is more intuitive??...

**Comment by e8035669** [comment]
Thanks for your reply.

It will be great if users can turn on or off this function when they need. 

I think making shortcut > checkbox > ratio button

If make a shortcut on the left hand side, users can press it easily by there left hand. Your work already has some shortcut function, add a new shortcut is more consistent I think.

Makeing a checkbox is also good, maybe a checkbox is intuitive than a shortcut. The main window usually has some empty space on the bottom right, we can put the checkbox there.

If make a ratio button, it will need a pair of ratio button, for one is turn on, another one is turn off. I think a checkbox is enough for now.

**Review by developer0hye — APPROVED** [review]

**Comment by developer0hye** [comment]
Closes #43

**Comment by developer0hye** [comment]
@e8035669 

Your code for exceptions is amazing!

**Pull request merged**
